Fixing compilation error for -Werror=uninitialized
../cocos2dx-store/Soomla/CCSoomlaNdkBridge.cpp:95:84: error:
‘retJsonParams’ is used uninitialized in this function [-
Werror=uninitialized]